- name: "Delete {{app_location}} directory if already exists"
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent
  ignore_errors: true

- name: "Create {{app_location}} directory"
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory

- name: "Download Artifact from Source Repo"
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
    dest: "/tmp/{{component}}.zip"

- name: "Unarchive Artifact in {{app_location}}"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: "{{app_location}}"
    remote_src: true
